# Generated by Django 5.1.2 on 2024-11-06 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "accounts",
            "0002_remove_customuser_address_remove_customuser_country_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="address",
            name="block",
            field=models.CharField(default="Unknown", max_length=100),
        ),
        migrations.AddField(
            model_name="address",
            name="is_home",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="address",
            name="is_office",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="address",
            name="is_other",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="address",
            name="post_office",
            field=models.CharField(default="Unknown", max_length=100),
        ),
        migrations.AddField(
            model_name="customuser",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="address",
            name="pincode",
            field=models.CharField(default=None, max_length=6),
        ),
    ]
