# Generated by Django 5.1.2 on 2024-11-12 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_address_block_address_is_home_address_is_office_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="address",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="address",
            name="mobile_number",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name="address",
            name="name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
