# Generated by Django 5.1.2 on 2024-11-14 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_address_email_address_mobile_number_address_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="is_vip",
            field=models.BooleanField(default=False),
        ),
    ]
