# Generated by Django 5.1.2 on 2024-12-24 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_customuser_permissions"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="address",
            name="post_office",
        ),
        migrations.AddField(
            model_name="address",
            name="landmark",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
