# Generated by Django 5.1.2 on 2024-10-21 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='cart',
            name='quantity',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='cart',
            name='size',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='cart',
            name='sleeve',
            field=models.CharField(max_length=5),
        ),
    ]
