# Generated by Django 5.1.2 on 2024-10-21 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_remove_cart_created_at_alter_cart_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='price',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='cart',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='cart',
            name='size',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='cart',
            name='sleeve',
            field=models.CharField(max_length=10),
        ),
    ]
