# Generated by Django 5.1.2 on 2024-11-02 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0004_alter_cart_price_alter_cart_size_alter_cart_sleeve"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cart",
            name="size",
            field=models.CharField(
                choices=[
                    ("S", "Small"),
                    ("M", "Medium"),
                    ("L", "Large"),
                    ("XL", "Extra Large"),
                    ("XXL", "2XL"),
                    ("XXXL", "3XL"),
                    ("4XL", "4XL"),
                ],
                max_length=6,
            ),
        ),
    ]
