# Generated by Django 5.1.2 on 2024-11-06 08:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0005_alter_cart_size"),
        ("products", "0005_rename_stock_in_meters_product_stock_length_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cart",
            name="free_product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="bogo_free_product",
                to="products.product",
            ),
        ),
    ]
