# Generated by Django 5.1.2 on 2024-11-12 19:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0006_cart_free_product"),
        ("products", "0007_remove_category_size_4xl_length_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cart",
            name="category_size",
            field=models.ForeignKey(
                blank=True,
                help_text="Select width and size options",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="products.categorysize",
            ),
        ),
        migrations.AddField(
            model_name="cart",
            name="length",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
        migrations.AlterField(
            model_name="cart",
            name="size",
            field=models.CharField(
                choices=[
                    ("L", "Large"),
                    ("XL", "Extra Large"),
                    ("XXL", "Double Extra Large"),
                    ("XXXL", "Triple Extra Large"),
                ],
                help_text="Select size (L, XL, XXL, etc.)",
                max_length=6,
            ),
        ),
        migrations.AlterField(
            model_name="cart",
            name="sleeve",
            field=models.CharField(
                choices=[("full", "Full Sleeve"), ("half", "Half Sleeve")],
                help_text="Select sleeve type (full, half, etc.)",
                max_length=10,
            ),
        ),
    ]
