# Generated by Django 5.1.2 on 2024-11-20 05:15

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0008_cart_free_product_size_cart_free_product_sleeve"),
        ("products", "0009_product_is_out_of_stock_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name="cart",
        #     name="category_size",
        # ),
        # migrations.RemoveField(
        #     model_name="cart",
        #     name="free_product",
        # ),
        # migrations.RemoveField(
        #     model_name="cart",
        #     name="free_product_size",
        # ),
        # migrations.RemoveField(
        #     model_name="cart",
        #     name="free_product_sleeve",
        # ),
        # migrations.RemoveField(
        #     model_name="cart",
        #     name="length",
        # ),
        # migrations.RemoveField(
        #     model_name="cart",
        #     name="price",
        # ),
        # migrations.RemoveField(
        #     model_name="cart",
        #     name="product",
        # ),
        # migrations.RemoveField(
        #     model_name="cart",
        #     name="quantity",
        # ),
        # migrations.RemoveField(
        #     model_name="cart",
        #     name="size",
        # ),
        # migrations.RemoveField(
        #     model_name="cart",
        #     name="sleeve",
        # ),
        # migrations.AddField(
        #     model_name="cart",
        #     name="created_at",
        #     field=models.DateTimeField(
        #         auto_now_add=True, default=django.utils.timezone.now
        #     ),
        #     preserve_default=False,
        # ),
        # migrations.AddField(
        #     model_name="cart",
        #     name="updated_at",
        #     field=models.DateTimeField(auto_now=True),
        # ),
        migrations.AlterField(
            model_name="cart",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.CreateModel(
            name="CartItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveIntegerField(default=1)),
                ("size", models.CharField(blank=True, max_length=6, null=True)),
                ("sleeve", models.CharField(blank=True, max_length=10, null=True)),
                (
                    "custom_length",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("length", models.DecimalField(decimal_places=2, max_digits=10)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("offer_type", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "discount_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "cart",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="cart.cart",
                    ),
                ),
                (
                    "free_product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cart_free_product",
                        to="products.product",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="products.product",
                    ),
                ),
            ],
        ),
    ]
