# Generated by Django 5.1.2 on 2024-11-20 05:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0009_remove_cart_category_size_remove_cart_free_product_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cart",
            name="category_size",
        ),
        migrations.RemoveField(
            model_name="cart",
            name="free_product",
        ),
        migrations.RemoveField(
            model_name="cart",
            name="free_product_size",
        ),
        migrations.RemoveField(
            model_name="cart",
            name="free_product_sleeve",
        ),
        migrations.RemoveField(
            model_name="cart",
            name="length",
        ),
        migrations.RemoveField(
            model_name="cart",
            name="price",
        ),
        migrations.RemoveField(
            model_name="cart",
            name="product",
        ),
        migrations.RemoveField(
            model_name="cart",
            name="quantity",
        ),
        migrations.RemoveField(
            model_name="cart",
            name="size",
        ),
        migrations.RemoveField(
            model_name="cart",
            name="sleeve",
        ),
        migrations.AddField(
            model_name="cart",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="cart",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
