# Generated by Django 5.1.2 on 2024-11-20 05:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0005_customuser_is_vip"),
        ("products", "0009_product_is_out_of_stock_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AdminOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("phoneNumber", models.CharField(max_length=15)),
                ("address", models.TextField()),
                ("state", models.CharField(max_length=255)),
                ("pincode", models.CharField(max_length=10)),
                ("city", models.CharField(max_length=255)),
                ("district", models.CharField(max_length=255)),
                ("size", models.CharField(blank=True, max_length=50, null=True)),
                ("customSize", models.CharField(blank=True, max_length=255, null=True)),
                ("quantity", models.PositiveIntegerField()),
                (
                    "paymentMethod",
                    models.CharField(
                        choices=[("COD", "Cash on Delivery"), ("Online", "Online")],
                        max_length=50,
                    ),
                ),
                (
                    "paymentStatus",
                    models.CharField(
                        choices=[("Pending", "Pending"), ("Completed", "Completed")],
                        max_length=50,
                    ),
                ),
                ("sleeveType", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "total_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "productCode",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="admin_orders",
                        to="products.product",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total_price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("Accept", "Accept"),
                            ("Reject", "Reject"),
                            ("Return", "Return"),
                            ("Completed", "Completed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("Track_id", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "return_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Return Initiated", "Return Initiated"),
                            ("Pending", "Pending"),
                            ("Completed", "Completed"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "payment_option",
                    models.CharField(
                        choices=[
                            ("COD", "Cash on Delivery"),
                            ("Razorpay", "Online Payment"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("Pending", "Pending"),
                            ("Paid", "Paid"),
                            ("Failed", "Failed"),
                        ],
                        default="Pending",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "shipping_address",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="accounts.address",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveIntegerField()),
                (
                    "size",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("L", "Large"),
                            ("XL", "Extra Large"),
                            ("XXL", "Double Extra Large"),
                            ("XXXL", "Triple Extra Large"),
                        ],
                        help_text="Select size (L, XL, XXL, etc.)",
                        max_length=6,
                        null=True,
                    ),
                ),
                (
                    "sleeve",
                    models.CharField(
                        blank=True,
                        choices=[("full", "Full Sleeve"), ("half", "Half Sleeve")],
                        help_text="Select sleeve type (full, half, etc.)",
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "custom_length",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("length", models.DecimalField(decimal_places=2, max_digits=10)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "free_product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="order_item_free_product",
                        to="products.product",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="orders.order",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="products.product",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TemporaryOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product_id", models.PositiveIntegerField()),
                ("quantity", models.PositiveIntegerField()),
                ("size", models.CharField(blank=True, max_length=6, null=True)),
                ("sleeve", models.CharField(blank=True, max_length=10, null=True)),
                (
                    "custom_length",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("length", models.DecimalField(decimal_places=2, max_digits=10)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("offer_type", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "discount_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("free_product", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
