# Generated by Django 5.1.2 on 2024-11-21 03:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
        ("products", "0009_product_is_out_of_stock_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="adminorder",
            name="customSize",
        ),
        migrations.RemoveField(
            model_name="adminorder",
            name="paymentMethod",
        ),
        migrations.RemoveField(
            model_name="adminorder",
            name="paymentStatus",
        ),
        migrations.RemoveField(
            model_name="adminorder",
            name="phoneNumber",
        ),
        migrations.RemoveField(
            model_name="adminorder",
            name="productCode",
        ),
        migrations.RemoveField(
            model_name="adminorder",
            name="sleeveType",
        ),
        migrations.AddField(
            model_name="adminorder",
            name="custom_length",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="adminorder",
            name="discount_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="adminorder",
            name="free_product",
            field=models.ForeignKey(
                blank=True,
                help_text="Free product, if any",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="admin_custom_order_free_product",
                to="products.product",
            ),
        ),
        migrations.AddField(
            model_name="adminorder",
            name="length",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="adminorder",
            name="offer_type",
            field=models.CharField(
                blank=True, help_text="Type of offer applied", max_length=20, null=True
            ),
        ),
        migrations.AddField(
            model_name="adminorder",
            name="payment_method",
            field=models.CharField(
                choices=[("COD", "Cash on Delivery"), ("Razorpay", "Online Payment")],
                default=1,
                help_text="Payment method",
                max_length=10,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="adminorder",
            name="payment_status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("Paid", "Paid"),
                    ("Failed", "Failed"),
                ],
                default="Pending",
                help_text="Payment status",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="adminorder",
            name="phone_number",
            field=models.CharField(
                default=1, help_text="Customer's contact number", max_length=15
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="adminorder",
            name="product",
            field=models.ForeignKey(
                default=1,
                help_text="Product being ordered",
                on_delete=django.db.models.deletion.CASCADE,
                to="products.product",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="adminorder",
            name="sleeve",
            field=models.CharField(
                blank=True,
                choices=[("full", "Full Sleeve"), ("half", "Half Sleeve")],
                help_text="Select sleeve type (full, half, etc.)",
                max_length=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="adminorder",
            name="address",
            field=models.TextField(help_text="Customer's address"),
        ),
        migrations.AlterField(
            model_name="adminorder",
            name="city",
            field=models.CharField(help_text="City", max_length=100),
        ),
        migrations.AlterField(
            model_name="adminorder",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, help_text="Order creation timestamp"
            ),
        ),
        migrations.AlterField(
            model_name="adminorder",
            name="district",
            field=models.CharField(help_text="District", max_length=100),
        ),
        migrations.AlterField(
            model_name="adminorder",
            name="name",
            field=models.CharField(help_text="Name of the customer", max_length=100),
        ),
        migrations.AlterField(
            model_name="adminorder",
            name="pincode",
            field=models.CharField(help_text="Pincode", max_length=6),
        ),
        migrations.AlterField(
            model_name="adminorder",
            name="size",
            field=models.CharField(
                blank=True,
                choices=[
                    ("L", "Large"),
                    ("XL", "Extra Large"),
                    ("XXL", "Double Extra Large"),
                    ("XXXL", "Triple Extra Large"),
                ],
                help_text="Select size (L, XL, XXL, etc.)",
                max_length=6,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="adminorder",
            name="state",
            field=models.CharField(help_text="State", max_length=100),
        ),
        migrations.AlterField(
            model_name="adminorder",
            name="total_price",
            field=models.DecimalField(
                decimal_places=2,
                default=1,
                help_text="Total price of the order",
                max_digits=10,
            ),
            preserve_default=False,
        ),
    ]
