# Generated by Django 5.1.2 on 2024-11-28 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0007_order_barcode_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="barcode_image",
        ),
    ]
