# Generated by Django 5.1.2 on 2024-12-02 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0009_remove_adminorder_custom_length_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="adminorder",
            name="Track_id",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="adminorder",
            name="city",
            field=models.CharField(
                blank=True, help_text="City", max_length=100, null=True
            ),
        ),
        migrations.AlterField(
            model_name="adminorder",
            name="district",
            field=models.CharField(
                blank=True, help_text="District", max_length=100, null=True
            ),
        ),
        migrations.AlterField(
            model_name="adminorder",
            name="pincode",
            field=models.CharField(
                blank=True, help_text="Pincode", max_length=6, null=True
            ),
        ),
        migrations.AlterField(
            model_name="adminorder",
            name="state",
            field=models.CharField(
                blank=True, help_text="State", max_length=100, null=True
            ),
        ),
    ]
