# Generated by Django 5.1.2 on 2024-12-07 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0011_order_rejected_reason"),
    ]

    operations = [
        migrations.AddField(
            model_name="adminorder",
            name="custom_return_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Return Initiated", "Return Initiated"),
                    ("Pending", "Pending"),
                    ("Completed", "Completed"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="adminorder",
            name="custom_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("Accept", "Accept"),
                    ("Reject", "Reject"),
                    ("Return", "Return"),
                    ("Completed", "Completed"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
