# Generated by Django 5.1.2 on 2024-12-09 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0017_alter_adminorder_is_online"),
    ]

    operations = [
        migrations.AddField(
            model_name="adminorder",
            name="rejected_reason",
            field=models.TextField(blank=True, null=True),
        ),
    ]
