# Generated by Django 5.1.2 on 2024-12-10 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0019_remove_adminorder_is_online_adminorder_order_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="adminorder",
            name="is_VIP",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="adminorder",
            name="is_favourite",
            field=models.BooleanField(default=False),
        ),
    ]
