# Generated by Django 5.1.2 on 2024-12-10 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0020_adminorder_is_vip_adminorder_is_favourite"),
    ]

    operations = [
        migrations.AlterField(
            model_name="adminorder",
            name="Order_options",
            field=models.CharField(
                default=True, help_text="True for Online, False for Shop", max_length=10
            ),
        ),
    ]
