# Generated by Django 5.1.2 on 2024-12-10 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0021_alter_adminorder_order_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="adminorder",
            name="Order_options",
            field=models.CharField(default="True", max_length=10),
        ),
    ]
