# Generated by Django 5.1.2 on 2024-12-13 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0024_alter_adminorder_order_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="adminorder",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("COD", "Cash on Delivery"),
                    ("Razorpay", "Online Payment"),
                    ("ShopPayment", "ShopPayment"),
                ],
                help_text="Payment method",
                max_length=12,
            ),
        ),
    ]
