# Generated by Django 5.1.2 on 2024-12-14 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0026_return_returnitem"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="payment_status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("Paid", "Paid"),
                    ("Failed", "Failed"),
                ],
                default="Paid",
                max_length=10,
            ),
        ),
    ]
