# Generated by Django 5.1.2 on 2024-10-21 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('color', models.CharField(max_length=50)),
                ('price_per_meter', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField()),
                ('image_1', models.ImageField(upload_to='products/images/')),
                ('image_2', models.ImageField(upload_to='products/images/')),
                ('stock_in_meters', models.DecimalField(decimal_places=2, max_digits=10)),
                ('size_S_length', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('size_M_length', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('size_L_length', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('size_XL_length', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('size_XXL_length', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('size_XXXL_length', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('size_XXXXL_length', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('size_XXXXXL_length', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('sleeve_half_length', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('sleeve_full_length', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
            ],
        ),
    ]
