# Generated by Django 5.1.2 on 2024-11-07 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0005_rename_stock_in_meters_product_stock_length_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="size_4XL_length",
        ),
        migrations.RemoveField(
            model_name="product",
            name="size_L_length",
        ),
        migrations.RemoveField(
            model_name="product",
            name="size_M_length",
        ),
        migrations.RemoveField(
            model_name="product",
            name="size_S_length",
        ),
        migrations.RemoveField(
            model_name="product",
            name="size_XL_length",
        ),
        migrations.RemoveField(
            model_name="product",
            name="size_XXL_length",
        ),
        migrations.RemoveField(
            model_name="product",
            name="size_XXXL_length",
        ),
        migrations.RemoveField(
            model_name="product",
            name="sleeve_full_length",
        ),
        migrations.RemoveField(
            model_name="product",
            name="sleeve_half_length",
        ),
        migrations.AddField(
            model_name="category",
            name="size_4XL_length",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="size_L_length",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="size_M_length",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="size_S_length",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="size_XL_length",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="size_XXL_length",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="size_XXXL_length",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="sleeve_full_length",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="sleeve_half_length",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
    ]
