# Generated by Django 5.1.2 on 2024-11-12 19:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0006_remove_product_size_4xl_length_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="size_4XL_length",
        ),
        migrations.RemoveField(
            model_name="category",
            name="size_L_length",
        ),
        migrations.RemoveField(
            model_name="category",
            name="size_M_length",
        ),
        migrations.RemoveField(
            model_name="category",
            name="size_S_length",
        ),
        migrations.RemoveField(
            model_name="category",
            name="size_XL_length",
        ),
        migrations.RemoveField(
            model_name="category",
            name="size_XXL_length",
        ),
        migrations.RemoveField(
            model_name="category",
            name="size_XXXL_length",
        ),
        migrations.RemoveField(
            model_name="category",
            name="sleeve_full_length",
        ),
        migrations.RemoveField(
            model_name="category",
            name="sleeve_half_length",
        ),
        migrations.AlterField(
            model_name="product",
            name="width",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Width in inches",
                max_digits=5,
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="CategorySize",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "width",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Width in inches (e.g., 44, 60, 120)",
                        max_digits=5,
                    ),
                ),
                (
                    "size_L_full_length",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "size_L_half_length",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "size_XL_full_length",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "size_XL_half_length",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "size_XXL_full_length",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "size_XXL_half_length",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "size_XXXL_full_length",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "size_XXXL_half_length",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sizes",
                        to="products.category",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="product",
            name="category_size",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="products",
                to="products.categorysize",
            ),
        ),
    ]
