# Generated by Django 5.1.2 on 2024-11-15 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0007_remove_category_size_4xl_length_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="category_size",
        ),
    ]
