# Generated by Django 5.1.2 on 2024-11-18 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0008_remove_product_category_size"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="is_out_of_stock",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="product",
            name="is_visible_in_listing",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="product",
            name="out_of_stock_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
