# Generated by Django 5.1.2 on 2024-11-22 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0010_testimonial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="wholesale_price_per_meter",
            field=models.DecimalField(
                decimal_places=2,
                default=1,
                help_text="Price per meter for wholesale purchase",
                max_digits=10,
            ),
            preserve_default=False,
        ),
    ]
