# Generated by Django 5.1.2 on 2024-11-25 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0011_product_wholesale_price_per_meter"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="invested_amount",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=15, null=True
            ),
        ),
    ]
