# Generated by Django 5.1.2 on 2024-12-26 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0014_alter_product_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="categorysize",
            name="width",
            field=models.CharField(
                help_text="Width in inches (e.g., 44, 60, 120)", max_length=5
            ),
        ),
    ]
